// src/lib/components/tabs/OverviewTab.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { Recipe, Style, EquipmentProfile } from "$lib/api";
  import { updateRecipe, listStyles, listEquipmentProfiles } from "$lib/api";

  let { recipe, onchange }: { recipe: Recipe; onchange: () => void } = $props();

  let styles = $state<Style[]>([]);
  let equipmentProfiles = $state<EquipmentProfile[]>([]);

  onMount(async () => {
    [styles, equipmentProfiles] = await Promise.all([listStyles(), listEquipmentProfiles()]);
  });

  async function save(field: string, value: unknown) {
    await updateRecipe(recipe.id, { [field]: value } as any);
    onchange();
  }

  const RECIPE_TYPES = ["all_grain", "extract", "partial_mash"] as const;
</script>

<div class="grid grid-cols-2 gap-4 max-w-2xl">
  <div class="flex flex-col gap-1">
    <label class="text-xs font-medium" style="color: var(--color-text-secondary);">Recipe Type</label>
    <select value={recipe.type_} onchange={(e) => save("type_", (e.target as HTMLSelectElement).value)}
            class="w-full px-2 py-1.5 rounded text-sm"
            style="background: var(--color-bg-elevated); color: var(--color-text-primary); border: 1px solid var(--color-border);">
      {#each RECIPE_TYPES as t}
        <option value={t}>{t.replace("_", " ")}</option>
      {/each}
    </select>
  </div>

  <div class="flex flex-col gap-1">
    <label class="text-xs font-medium" style="color: var(--color-text-secondary);">Brewer</label>
    <input type="text" value={recipe.brewer ?? ""}
           onblur={(e) => save("brewer", (e.target as HTMLInputElement).value)}
           class="w-full px-2 py-1.5 rounded text-sm"
           style="background: var(--color-bg-elevated); color: var(--color-text-primary); border: 1px solid var(--color-border);" />
  </div>

  <div class="flex flex-col gap-1">
    <label class="text-xs font-medium" style="color: var(--color-text-secondary);">Batch Size (L)</label>
    <input type="number" step="0.1" value={recipe.batch_size_l}
           onblur={(e) => save("batch_size_l", parseFloat((e.target as HTMLInputElement).value))}
           class="w-full px-2 py-1.5 rounded text-sm"
           style="background: var(--color-bg-elevated); color: var(--color-text-primary); border: 1px solid var(--color-border);" />
  </div>

  <div class="flex flex-col gap-1">
    <label class="text-xs font-medium" style="color: var(--color-text-secondary);">Boil Size (L)</label>
    <input type="number" step="0.1" value={recipe.boil_size_l}
           onblur={(e) => save("boil_size_l", parseFloat((e.target as HTMLInputElement).value))}
           class="w-full px-2 py-1.5 rounded text-sm"
           style="background: var(--color-bg-elevated); color: var(--color-text-primary); border: 1px solid var(--color-border);" />
  </div>

  <div class="flex flex-col gap-1">
    <label class="text-xs font-medium" style="color: var(--color-text-secondary);">Boil Time (min)</label>
    <input type="number" step="5" value={recipe.boil_time_min}
           onblur={(e) => save("boil_time_min", parseFloat((e.target as HTMLInputElement).value))}
           class="w-full px-2 py-1.5 rounded text-sm"
           style="background: var(--color-bg-elevated); color: var(--color-text-primary); border: 1px solid var(--color-border);" />
  </div>

  <div class="flex flex-col gap-1">
    <label class="text-xs font-medium" style="color: var(--color-text-secondary);">Efficiency (%)</label>
    <input type="number" step="1" value={recipe.efficiency_pct ?? ""}
           placeholder="From equipment profile"
           onblur={(e) => {
             const v = (e.target as HTMLInputElement).value;
             save("efficiency_pct", v ? parseFloat(v) : null);
           }}
           class="w-full px-2 py-1.5 rounded text-sm"
           style="background: var(--color-bg-elevated); color: var(--color-text-primary); border: 1px solid var(--color-border);" />
  </div>

  <div class="flex flex-col gap-1">
    <label class="text-xs font-medium" style="color: var(--color-text-secondary);">Equipment Profile</label>
    <select value={recipe.equipment_profile_id ?? ""}
            onchange={(e) => save("equipment_profile_id", (e.target as HTMLSelectElement).value || null)}
            class="w-full px-2 py-1.5 rounded text-sm"
            style="background: var(--color-bg-elevated); color: var(--color-text-primary); border: 1px solid var(--color-border);">
      <option value="">None</option>
      {#each equipmentProfiles as ep}
        <option value={ep.id}>{ep.name}</option>
      {/each}
    </select>
  </div>

  <div class="flex flex-col gap-1">
    <label class="text-xs font-medium" style="color: var(--color-text-secondary);">Style</label>
    <select value={recipe.style_id ?? ""}
            onchange={(e) => save("style_id", (e.target as HTMLSelectElement).value || null)}
            class="w-full px-2 py-1.5 rounded text-sm"
            style="background: var(--color-bg-elevated); color: var(--color-text-primary); border: 1px solid var(--color-border);">
      <option value="">None</option>
      {#each styles as s}
        <option value={s.id}>{s.name}</option>
      {/each}
    </select>
  </div>

  <div class="flex flex-col gap-1">
    <label class="text-xs font-medium" style="color: var(--color-text-secondary);">Date</label>
    <input type="date" value={recipe.date ?? ""}
           onblur={(e) => save("date", (e.target as HTMLInputElement).value || null)}
           class="w-full px-2 py-1.5 rounded text-sm"
           style="background: var(--color-bg-elevated); color: var(--color-text-primary); border: 1px solid var(--color-border);" />
  </div>
</div>

// design/ui_kits/brewski-desktop/OverviewTab.jsx
// OverviewTab — first tab of a recipe. Two cards: details + volumes.

function Field({ label, children }) {
  return (
    <div className="field">
      <label>{label}</label>
      {children}
    </div>
  );
}

function OverviewTab({ recipe, onChange }) {
  const set = (k, v) => onChange({ ...recipe, [k]: v });
  return (
    <div className="gap-4 maxw-2xl">
      <window.Card title="Recipe Details">
        <div className="grid-2">
          <Field label="Recipe Type">
            <select value={recipe.type} onChange={(e) => set("type", e.target.value)}>
              <option value="all_grain">all grain</option>
              <option value="extract">extract</option>
              <option value="partial_mash">partial mash</option>
            </select>
          </Field>
          <Field label="Brewer">
            <input value={recipe.brewer} onChange={(e) => set("brewer", e.target.value)} />
          </Field>
          <Field label="Style">
            <input value={recipe.style} onChange={(e) => set("style", e.target.value)} />
          </Field>
          <Field label="Date">
            <input type="date" value={recipe.date || ""} onChange={(e) => set("date", e.target.value)} />
          </Field>
          <div className="field" style={{ gridColumn: "1 / -1" }}>
            <label>Equipment Profile</label>
            <select defaultValue="">
              <option value="">None</option>
              <option>10 gal Anvil Foundry</option>
              <option>5 gal Brew-in-a-Bag</option>
            </select>
          </div>
        </div>
      </window.Card>

      <window.Card title="Volumes & Timing">
        <div className="grid-2">
          <Field label="Batch Size (gal)">
            <input type="number" step="0.1" value={recipe.batch_size_gal}
              onChange={(e) => set("batch_size_gal", parseFloat(e.target.value) || 0)} />
          </Field>
          <Field label="Boil Size (gal)">
            <input type="number" step="0.1" value={recipe.boil_size_gal}
              onChange={(e) => set("boil_size_gal", parseFloat(e.target.value) || 0)} />
          </Field>
          <Field label="Boil Time (min)">
            <input type="number" step="5" value={recipe.boil_time_min}
              onChange={(e) => set("boil_time_min", parseFloat(e.target.value) || 0)} />
          </Field>
          <Field label="Efficiency (%)">
            <input type="number" step="1" value={recipe.efficiency_pct}
              onChange={(e) => set("efficiency_pct", parseFloat(e.target.value) || 0)} />
          </Field>
        </div>
      </window.Card>

      {recipe.notes && (
        <window.Card title="Notes">
          <p style={{ margin: 0, fontSize: 14, lineHeight: 1.5, color: "var(--color-text-primary)" }}>
            {recipe.notes}
          </p>
        </window.Card>
      )}
    </div>
  );
}

window.OverviewTab = OverviewTab;
