// src/lib/components/TabBar.svelte
<!-- src/lib/components/TabBar.svelte -->
<script lang="ts">
  import BrewingIcon from "$lib/components/BrewingIcon.svelte";
  import type { BrewingIconName } from "$lib/icons";

  interface Tab {
    key: string;
    label: string;
    icon?: BrewingIconName;
  }

  let {
    tabs,
    active,
    onchange,
  }: {
    tabs: readonly Tab[];
    active: string;
    onchange: (key: string) => void;
  } = $props();
</script>

<div class="flex gap-0 border-b" style="border-color: var(--color-border);">
  {#each tabs as tab}
    <button
      onclick={() => onchange(tab.key)}
      class="px-4 py-2.5 text-sm transition-colors inline-flex items-center gap-1.5 border-b-2 -mb-px"
      style={active === tab.key
        ? "color: var(--color-accent); border-color: var(--color-accent); background: transparent;"
        : "color: var(--color-text-secondary); border-color: transparent; background: transparent;"}
    >
      {#if tab.icon}
        <span style={active === tab.key ? "opacity: 1;" : "opacity: 0.45;"}>
          <BrewingIcon name={tab.icon} size={20} />
        </span>
      {/if}
      {tab.label}
    </button>
  {/each}
</div>

// design/ui_kits/brewski-desktop/TabBar.jsx
// TabBar — the recipe sub-tab bar (Overview, Ingredients, Mash, …).
// Brewing icon + text label, 2px accent underline on active.

function TabBar({ tabs, active, onChange }) {
  return (
    <div className="tabbar">
      {tabs.map((t) => (
        <button
          key={t.key}
          onClick={() => onChange(t.key)}
          className={"tab" + (active === t.key ? " active" : "")}
        >
          {t.icon && <window.BrewingIcon name={t.icon} size={18} />}
          {t.label}
        </button>
      ))}
    </div>
  );
}

window.TabBar = TabBar;
