// design/ui_kits/brewski-desktop/StatsSidebar.jsx
// StatsSidebar — the 176px right rail with live brew stats.
// Mirrors src/lib/components/StatsSidebar.svelte.

function StatItem({ label, value, unit, progress, progressColor }) {
  return (
    <div className="stat-card">
      <div className="lbl">{label}</div>
      <div className="val">
        {value}{unit && <span className="unit">{unit}</span>}
      </div>
      {progress !== undefined && (
        <div className="bar">
          <div style={{ width: `${Math.min(100, Math.max(0, progress * 100))}%`, background: progressColor || "var(--color-accent)" }} />
        </div>
      )}
    </div>
  );
}

function StatsSidebar({ recipe }) {
  if (!recipe) {
    return (
      <aside className="stats">
        <p className="h-eyebrow-x" style={{ marginBottom: 4 }}>Stats</p>
        <p style={{ fontSize: 12, color: "var(--color-text-muted)" }}>
          Add ingredients to see stats
        </p>
      </aside>
    );
  }

  const pct = (v, min, max) => (v - min) / (max - min);

  return (
    <aside className="stats">
      <p className="h-eyebrow-x" style={{ marginBottom: 4 }}>Stats</p>
      <StatItem label="OG"     value={recipe.og.toFixed(3)}     progress={pct(recipe.og, 1.000, 1.120)} />
      <StatItem label="FG"     value={recipe.fg.toFixed(3)}     progress={pct(recipe.fg, 1.000, 1.030)} />
      <StatItem label="ABV"    value={recipe.abv.toFixed(1)} unit="%" progress={pct(recipe.abv, 0, 12)} progressColor="#a6e3a1" />
      <StatItem label="IBU"    value={recipe.ibu.toFixed(0)}    progress={pct(recipe.ibu, 0, 120)}     progressColor="#fab387" />

      <div className="stat-card">
        <div className="lbl">SRM</div>
        <div className="val" style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <span style={{ width: 18, height: 18, borderRadius: 4, background: window.srmToHex(recipe.srm), border: "1px solid rgba(255,255,255,0.15)", flexShrink: 0 }} />
          {recipe.srm.toFixed(1)}
        </div>
      </div>

      <StatItem label="BU:GU"     value={recipe.bu_gu.toFixed(2)} />
      <StatItem label="Cal / 12oz" value={recipe.cal_per_12oz} />

      <p className="h-eyebrow-x" style={{ marginTop: 6, marginBottom: 2 }}>Volumes</p>
      <StatItem label="Pre-boil"   value={recipe.pre_boil_vol.toFixed(1)} unit=" gal" />
      <StatItem label="Post-boil"  value={recipe.post_boil_vol.toFixed(1)} unit=" gal" />
      <StatItem label="Pre-boil G" value={recipe.pre_boil_g.toFixed(3)} />
    </aside>
  );
}

window.StatsSidebar = StatsSidebar;

// src/lib/components/StatsSidebar.svelte
<!-- src/lib/components/StatsSidebar.svelte -->
<script lang="ts">
  import type { RecipeStats } from "$lib/api";
  import { settings } from "$lib/stores/settings";
  import { type Units, lToGal, volumeLabel } from "$lib/units";
  import { srmToHex } from "$lib/utils/srm";
  import { formatSg } from "$lib/gravity-display";

  let { stats }: { stats: RecipeStats | null } = $props();

  const units = $derived<Units>($settings.units === "imperial" ? "imperial" : "metric");
  const gravityUnit = $derived($settings.gravity_unit ?? "sg");

  const displayOg = $derived(stats?.og != null ? formatSg(stats.og, gravityUnit) : "—");
  const displayFg = $derived(stats?.fg != null ? formatSg(stats.fg, gravityUnit) : "—");
  const displayPreBoil = $derived(
    stats?.pre_boil_gravity != null ? formatSg(stats.pre_boil_gravity, gravityUnit) : "—",
  );

  function fmt(val: number | undefined | null, decimals = 3): string {
    if (val === undefined || val === null) return "—";
    return val.toFixed(decimals);
  }

  function pct(value: number, min: number, max: number): number {
    return Math.min(100, Math.max(0, ((value - min) / (max - min)) * 100));
  }
</script>

<aside class="w-44 flex-shrink-0 flex flex-col border-l overflow-y-auto p-3 gap-1.5 bg-bg-surface border-border"
      >
  <p class="text-xs font-semibold uppercase tracking-wider mb-1 text-text-muted"
    >Stats</p>

  {#if stats}
    <!-- OG -->
    <div class="rounded-lg p-2.5 bg-bg-elevated border border-border">
      <p class="text-xs mb-0.5 text-text-muted">OG</p>
      <p class="text-xl font-bold font-mono leading-none text-text-primary">{displayOg}</p>
      <div class="mt-1.5 h-1 rounded-full bg-border">
        <div class="h-full rounded-full" style="width: {pct(stats.og, 1.000, 1.120)}%; background: var(--color-accent);"></div>
      </div>
    </div>

    <!-- FG -->
    <div class="rounded-lg p-2.5 bg-bg-elevated border border-border">
      <p class="text-xs mb-0.5 text-text-muted">FG</p>
      <p class="text-xl font-bold font-mono leading-none text-text-primary">{displayFg}</p>
      <div class="mt-1.5 h-1 rounded-full bg-border">
        <div class="h-full rounded-full" style="width: {pct(stats.fg, 1.000, 1.030)}%; background: var(--color-accent);"></div>
      </div>
    </div>

    <!-- ABV -->
    <div class="rounded-lg p-2.5 bg-bg-elevated border border-border">
      <p class="text-xs mb-0.5 text-text-muted">ABV</p>
      <p class="text-xl font-bold font-mono leading-none text-text-primary">
        {fmt(stats.abv_pct, 1)}<span class="text-sm font-normal text-text-muted">%</span>
      </p>
      <div class="mt-1.5 h-1 rounded-full bg-border">
        <div class="h-full rounded-full" style="width: {pct(stats.abv_pct, 0, 12)}%; background: #a6e3a1;"></div>
      </div>
    </div>

    <!-- IBU -->
    <div class="rounded-lg p-2.5 bg-bg-elevated border border-border">
      <p class="text-xs mb-0.5 text-text-muted">IBU</p>
      <p class="text-xl font-bold font-mono leading-none text-text-primary">{fmt(stats.ibu, 0)}</p>
      <div class="mt-1.5 h-1 rounded-full bg-border">
        <div class="h-full rounded-full" style="width: {pct(stats.ibu, 0, 120)}%; background: #fab387;"></div>
      </div>
    </div>

    <!-- SRM -->
    <div class="rounded-lg p-2.5 bg-bg-elevated border border-border">
      <p class="text-xs mb-0.5 text-text-muted">SRM</p>
      <div class="flex items-center gap-2">
        <div class="w-5 h-5 rounded flex-shrink-0"
             style="background: {srmToHex(stats.srm)}; border: 1px solid rgba(255,255,255,0.15);"></div>
        <p class="text-xl font-bold font-mono leading-none text-text-primary">{fmt(stats.srm, 1)}</p>
      </div>
    </div>

    <!-- BU:GU -->
    <div class="rounded-lg p-2.5 bg-bg-elevated border border-border">
      <p class="text-xs mb-0.5 text-text-muted">BU:GU</p>
      <p class="text-xl font-bold font-mono leading-none text-text-primary">{fmt(stats.bu_gu_ratio, 2)}</p>
    </div>

    <!-- Calories -->
    <div class="rounded-lg p-2.5 bg-bg-elevated border border-border">
      <p class="text-xs mb-0.5 text-text-muted">Cal / 12oz</p>
      <p class="text-xl font-bold font-mono leading-none text-text-primary">{fmt(stats.calories_per_355ml, 0)}</p>
    </div>

    <!-- Volumes divider -->
    <p class="text-xs font-semibold uppercase tracking-wider mt-1 mb-0.5 text-text-muted"
      >Volumes</p>

    <!-- Pre-boil -->
    <div class="rounded-lg p-2.5 bg-bg-elevated border border-border">
      <p class="text-xs mb-0.5 text-text-muted">Pre-boil</p>
      <p class="text-base font-bold font-mono leading-none text-text-primary">
        {fmt(units === "imperial" ? lToGal(stats.pre_boil_volume_l) : stats.pre_boil_volume_l, 1)}<span class="text-xs font-normal ml-0.5 text-text-muted">{volumeLabel(units)}</span>
      </p>
    </div>

    <!-- Post-boil -->
    <div class="rounded-lg p-2.5 bg-bg-elevated border border-border">
      <p class="text-xs mb-0.5 text-text-muted">Post-boil</p>
      <p class="text-base font-bold font-mono leading-none text-text-primary">
        {fmt(units === "imperial" ? lToGal(stats.post_boil_volume_l) : stats.post_boil_volume_l, 1)}<span class="text-xs font-normal ml-0.5 text-text-muted">{volumeLabel(units)}</span>
      </p>
    </div>

    <!-- Pre-boil gravity -->
    <div class="rounded-lg p-2.5 bg-bg-elevated border border-border">
      <p class="text-xs mb-0.5 text-text-muted">Pre-boil G</p>
      <p class="text-base font-bold font-mono leading-none text-text-primary">{displayPreBoil}</p>
    </div>

  {:else}
    <p class="text-xs text-text-muted">Add ingredients to see stats</p>
  {/if}
</aside>
